#!/usr/bin/env python

import rospy

from sensor_msgs.msg import NavSatFix

import random


class FakeGps():

    def __init__(self):
        self.publisher = rospy.Publisher("fix", NavSatFix, queue_size=10)
        self.msg = NavSatFix()
        self.c = 0
        self.set_msg()

    def set_msg(self):
        self.msg.latitude = 50.076673857412935
        self.msg.longitude = 14.41751975802257
        self.msg.altitude = 200.0

        self.c += 1

        self.msg.position_covariance = [0]*9
        self.msg.position_covariance[0] = 1
        self.msg.position_covariance[4] = 1
        self.msg.position_covariance[8] = 1

        self.msg.header.stamp = rospy.Time.now()
        self.msg.header.frame_id = "gps"
        self.msg.status.status = 0
        self.msg.status.service = 1

    def run(self):
        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.msg.header.stamp = rospy.Time.now()
            self.msg.latitude += 0.00002 * random.gauss(0,1)
            self.msg.longitude += 0.00002 * random.gauss(0,1)
            self.publisher.publish(self.msg)
            rate.sleep()


if __name__ == "__main__":
    rospy.init_node("fake_gps")
    node = FakeGps()
    node.run()
