#!/usr/bin/env python

import rospy

from stamped_msgs.msg import Float64


class FakeMagAzimuth():

    def __init__(self):
        self.publisher = rospy.Publisher('mag_azimuth', Float64, queue_size=10)
        self.msg = Float64()
        self.msg.data = 72.

    def run(self):
        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.msg.header.stamp = rospy.Time.now()
            self.publisher.publish(self.msg)
            rate.sleep()


if __name__ == "__main__":
    rospy.init_node("fake_mag_azimuth")
    node = FakeMagAzimuth()
    node.run()
