#!/usr/bin/env python
"""
Node for sending fake Path to robot.
"""

import rospy
from nav_msgs.msg import Path
import std_msgs.msg
from geometry_msgs.msg import PoseStamped


if __name__ == '__main__':
    rospy.init_node('fake_path')
    rate = rospy.Rate(10)
    pub = rospy.Publisher('path', Path, queue_size=10)
    msg = Path()

    header = std_msgs.msg.Header()
    
    poses = PoseStamped()
    poses.pose.position.x = 0.7
    poses.pose.position.y = 0.

    msg.poses.append(poses)

    while not rospy.is_shutdown():
        header.stamp = rospy.Time.now()
        header.frame_id = "map"
        msg.header = header
        msg.poses[0].header = header
        pub.publish(msg)
        rate.sleep()
