#!/usr/bin/env python

import rospy
import std_msgs
from gps_to_path.msg import MagShift
from sensor_msgs.msg import MagneticField


class MagShiftCalc():
    def __init__(self, measuring_time):

        self.x_min = 10000
        self.y_min = 10000
        self.z_min = 10000

        self.x_max = -10000
        self.y_max = -10000
        self.z_max = -10000

        self.x_mean = None
        self.y_mean = None
        self.z_mean = None

        self.msg = MagShift()

        self.measuring_time = measuring_time
        self.finish_measuring_time = rospy.Time.now().to_sec() + self.measuring_time

        self.pub = rospy.Publisher('mag_shift', MagShift, queue_size=10)
        self.sub = rospy.Subscriber(
            '/imu/mag', MagneticField, self.mag_callback)

    def mag_callback(self, msg):
        if rospy.Time.now().to_sec() < self.finish_measuring_time:
            mag = msg.magnetic_field

            if mag.x > self.x_max:
                self.x_max = mag.x
            elif mag.x < self.x_min:
                self.x_min = mag.x

            if mag.y > self.y_max:
                self.y_max = mag.y
            elif mag.y < self.y_min:
                self.y_min = mag.y

            if mag.z > self.z_max:
                self.z_max = mag.z
            elif mag.z < self.z_min:
                self.z_min = mag.z

            self.set_means()
        else:
            rospy.logwarn_once("Finished measuring ")

        self.pub_msg()

    def set_means(self):
        self.x_mean = (self.x_min + self.x_max)/2
        self.y_mean = (self.y_min + self.y_max)/2
        self.z_mean = (self.z_min + self.z_max)/2

    def pub_msg(self):
        header = std_msgs.msg.Header()
        header.stamp = rospy.Time.now()
        header.frame_id = "imu"

        self.msg.header = header

        self.msg.x_mean = self.x_mean
        self.msg.y_mean = self.y_mean
        self.msg.z_mean = self.z_mean

        self.pub.publish(self.msg)

    def run(self):
        rospy.spin()


def main():
    rospy.init_node('mag_shift')

    measuring_time = rospy.get_param('~measuring_time', 30)
    node = MagShiftCalc(measuring_time)
    node.run()


if __name__ == '__main__':
    main()
