#!/usr/bin/env python

import osm_analysis_igraph
import rospy
import numpy as np
import pickle
import shapely.geometry as geometry

rospy.init_node('osm_only_node')

gpx_pre = "/home/robot/0923/src/gps-navigation/gps_to_path/data/"
gpx_file_names = ["CH-forest-north_short_circle_debug.gpx"]#"unhost_final_demo_spot_east_trimmed.gpx"]

for fn in gpx_file_names:
    fn = gpx_pre + fn
    osm_planner = osm_analysis_igraph.PathAnalysis(fn,
                                                    True,
                                                    np.array([[459595,5553117]]),
                                                    #np.array([[438006,5549044]]),
                                                    True,
                                                    False,
                                                    False)
    osm_planner.run_ros()

    with open(fn[:-4]+'.osm_planner', 'wb') as handle:
        pickle.dump(osm_planner, handle, protocol=pickle.HIGHEST_PROTOCOL)

""" with open('/home/robot/0923/src/gps-navigation/gps_to_path/data/unhost_final_demo_spot_east', 'rb') as handle:
    b = pickle.load(handle)

b.sub_graphs.pop(0)

first_waypoint = geometry.Point(np.ravel(b.sub_graphs[0]['graph_points'][b.sub_graphs[0]['goal_index_graph']]))
current_position_point = geometry.Point(np.ravel(np.array([[438000, 5549040]])))
current_pos_to_start_point_graph = b.generate_graph(current_position_point, first_waypoint)

# ... with current position of robot to first waypoint.
b.sub_graphs.insert(0, current_pos_to_start_point_graph)
sub_graph_ind = 0

#print(b.sub_graphs) """