LEVEL_0_WEIGHT = 0.75
LEVEL_1_WEIGHT = 3
LEVEL_2_WEIGHT = 6
LEVEL_3_WEIGHT = 10
LEVEL_4_WEIGHT = 20
LEVEL_5_WEIGHT = 30

LEVEL_1_MAX_RADIUS = 220
LEVEL_2_MAX_RADIUS = 150
LEVEL_3_MAX_RADIUS = 90
LEVEL_4_MAX_RADIUS = 40

ROAD_CURVATURE_RANKS = 15
ROAD_CLASS_RANKS = 5
ROAD_ELEVATION_RANKS = 9
ROAD_CROSSINGS_RANKS = 15

CURVATURE_WEIGHT = 9
CLASS_WEIGHT = 1
ELEVATION_WEIGHT = None

SMALL_NEIGH = 3
LARGE_NEIGH = 7
SMALL_CHANGE = 0.3
LARGE_CHANGE = 0.7

CANYONS = 8
MIDSLOPE_DRAIN = 5
UPLAND_DRAIN = 6
U_VALLEY = 2
PLAINS = 1
OPEN_SLOPES = 3
UPPER_SLOPES = 6
LOCAL_RIDGE = 8
MIDSLOPE_RIDGE = 10
MOUNTAIN_TOP = 15
