#!/usr/bin/env python
"""Converts Waypoints to Path messages."""
import rospy
from nav_msgs.msg import Path
from geometry_msgs.msg import Point, PoseStamped
from gps_to_path.msg import Waypoints
import numpy as np
from ros_numpy import numpify
from tf2_ros import Buffer, TransformException, TransformListener


class WaypointsToPath(object):
    def __init__(self):
        self.tf = Buffer()
        self.tf_sub = TransformListener(self.tf)
        self.target_frame = rospy.get_param('~target_frame', 'gps_odom')
        self.constant_z = rospy.get_param('~constant_z', None)
        self.z_frame = rospy.get_param('~z_frame', 'base_link')
        self.timeout = rospy.get_param('~timeout', 1.0)

        self.path_pub = rospy.Publisher('path', Path, queue_size=2)
        self.waypoints_sub = rospy.Subscriber('waypoints', Waypoints, self.convert, queue_size=2)

    def convert(self, msg):
        assert isinstance(msg, Waypoints)

        # Get z from z frame if available or use constant.
        z = None
        if self.target_frame and self.z_frame:
            try:
                tf = self.tf.lookup_transform(self.target_frame, self.z_frame, msg.header.stamp,
                                              rospy.Duration.from_sec(self.timeout))
                tf = numpify(tf.transform)
                z = tf[2, 3]
            except TransformException as ex:
                rospy.logerr('Could not transform from %s to %s at time %.3f.',
                             self.z_frame, self.target_frame, msg.header.stamp.to_sec())
                return
        elif self.constant_z is not None:
            z = self.constant_z

        # Get transform from waypoints frame to target frame.
        tf = np.eye(4)
        if self.target_frame and self.target_frame != msg.header.frame_id:
            try:
                tf = self.tf.lookup_transform(self.target_frame, msg.header.frame_id, msg.header.stamp,
                                              rospy.Duration.from_sec(self.timeout))
                tf = numpify(tf.transform)
            except TransformException as ex:
                rospy.logerr('Could not transform from %s to %s at time %.3f.',
                             msg.header.frame_id, self.target_frame, msg.header.stamp.to_sec())
                return

        path_msg = Path()
        path_msg.header.frame_id = self.target_frame
        path_msg.header.stamp = msg.header.stamp

        for pt in msg.points:
            assert isinstance(pt, Point)
            pose = PoseStamped()
            pose.header = path_msg.header
            pose.pose.orientation.w = 1.0
            x = np.array([[pt.x], [pt.y], [pt.z], [1.0]])
            y = np.matmul(tf, x)
            pose.pose.position.x = y[0, 0]
            pose.pose.position.y = y[1, 0]
            if z is None:
                pose.pose.position.z = y[2, 0]
            else:
                pose.pose.position.z = z
            path_msg.poses.append(pose)
        self.path_pub.publish(path_msg)

def main():
    rospy.init_node('waypoints_to_path')
    node = WaypointsToPath()
    rospy.spin()


if __name__ == '__main__':
    main()
